/**
 * CODES DE REJET MÉTIER — identifiants STABLES, jamais affichés tels quels.
 *
 * Un code existe pour que le CLIENT puisse décider quoi faire, et dans quelle
 * LANGUE le dire, sans lire le texte du serveur. Deux raisons, et la seconde a
 * déjà mordu :
 *
 *   1. Le runtime Convex n'a ni requête, ni cookie, ni `Accept-Language`. Il ne
 *      PEUT PAS savoir dans quelle langue écrire. Un message figé côté serveur
 *      angliciserait l'admin en même temps que le créateur, ou l'inverse — ces
 *      rejets sortent de cœurs PARTAGÉS (`confirmPublicationCore`,
 *      `declareCompteCore`…), atteints par les deux populations.
 *   2. `AdminPublishForm` branchait son flux de régularisation de date sur
 *      `/précède la\s+création/i`. Traduire le message cassait le flux en
 *      silence — ni erreur de compilation, ni test rouge.
 *
 * ⚠️ Un code ne se renomme pas. Il vit dans le protocole entre le serveur et le
 * client, comme un nom de champ de schéma.
 *
 * Le module vit dans `convex/` : le runtime Convex n'importe rien hors de
 * `convex/` (règle A6), et `lib/` peut l'importer dans ce sens-là.
 *
 * GÉNÉRÉ EN PARTIE — le tableau ci-dessous est la source des clés i18n
 * `error.<code>` : les deux catalogues portent une entrée par code.
 */
import { ConvexError } from "convex/values";

export const ERR = {
  TARGETS_COUNT: "ERR_TARGETS_COUNT",
  TARGET_ACCOUNT_NOT_FOUND_FOR_CREATOR: "ERR_TARGET_ACCOUNT_NOT_FOUND_FOR_CREATOR",
  TARGETS_MIXED_OWNERSHIP: "ERR_TARGETS_MIXED_OWNERSHIP",
  FORMAT_NOT_FOUND: "ERR_FORMAT_NOT_FOUND",
  FORMAT_ARCHIVED: "ERR_FORMAT_ARCHIVED",
  VIDEO_COUNT_INVALID: "ERR_VIDEO_COUNT_INVALID",
  CREATOR_NOT_IN_PROJECT: "ERR_CREATOR_NOT_IN_PROJECT",
  ASSIGNMENT_NOT_FOUND: "ERR_ASSIGNMENT_NOT_FOUND",
  ASSET_FOLDER_NOT_FOUND: "ERR_ASSET_FOLDER_NOT_FOUND",
  ASSIGNMENT_ALREADY_STARTED: "ERR_ASSIGNMENT_ALREADY_STARTED",
  VIDEO_SUBMIT_WRONG_STATE: "ERR_VIDEO_SUBMIT_WRONG_STATE",
  ASSIGNMENT_NO_TARGET: "ERR_ASSIGNMENT_NO_TARGET",
  PUBLISHED_AT_IN_FUTURE: "ERR_PUBLISHED_AT_IN_FUTURE",
  ACCOUNT_MANAGED_PUBLISH: "ERR_ACCOUNT_MANAGED_PUBLISH",
  TARGET_ACCOUNT_NOT_IN_PROJECT: "ERR_TARGET_ACCOUNT_NOT_IN_PROJECT",
  ACCOUNT_NOT_FOUND: "ERR_ACCOUNT_NOT_FOUND",
  MANAGED_ACCOUNT_NEEDS_CREATOR: "ERR_MANAGED_ACCOUNT_NEEDS_CREATOR",
  ACCOUNT_PLATFORM_LOCKED: "ERR_ACCOUNT_PLATFORM_LOCKED",
  WARMUP_START_REQUIRED: "ERR_WARMUP_START_REQUIRED",
  NO_BIO_TO_APPLY: "ERR_NO_BIO_TO_APPLY",
  HANDLE_REQUIRED: "ERR_HANDLE_REQUIRED",
  ACCOUNT_NOT_IN_WARMUP: "ERR_ACCOUNT_NOT_IN_WARMUP",
  WARMUP_ALREADY_DONE: "ERR_WARMUP_ALREADY_DONE",
  WARMUP_CHECK_ALREADY_DONE: "ERR_WARMUP_CHECK_ALREADY_DONE",
  ACCOUNT_MANAGED_WARMUP: "ERR_ACCOUNT_MANAGED_WARMUP",
  ACCOUNT_NOT_MANAGED: "ERR_ACCOUNT_NOT_MANAGED",
  NOT_AUTHENTICATED: "ERR_NOT_AUTHENTICATED",
  PROJECT_NOT_FOUND: "ERR_PROJECT_NOT_FOUND",
  PROJECT_ACCESS_DENIED: "ERR_PROJECT_ACCESS_DENIED",
  ADMIN_ONLY: "ERR_ADMIN_ONLY",
  CREATOR_RECORD_NOT_FOUND: "ERR_CREATOR_RECORD_NOT_FOUND",
  CREATOR_NOT_IN_THIS_PROJECT: "ERR_CREATOR_NOT_IN_THIS_PROJECT",
  RESET_LINK_INVALID: "ERR_RESET_LINK_INVALID",
  OPERATION_NOT_ALLOWED: "ERR_OPERATION_NOT_ALLOWED",
  ACCOUNT_HAS_NO_PASSWORD: "ERR_ACCOUNT_HAS_NO_PASSWORD",
  PASSWORD_TOO_SHORT: "ERR_PASSWORD_TOO_SHORT",
  CREATOR_NOT_FOUND: "ERR_CREATOR_NOT_FOUND",
  NO_PAY_CYCLE: "ERR_NO_PAY_CYCLE",
  CYCLE_INVALID: "ERR_CYCLE_INVALID",
  PAYMENT_NOT_FOUND: "ERR_PAYMENT_NOT_FOUND",
  PAYMENT_NOT_PAID: "ERR_PAYMENT_NOT_PAID",
  PAYMENT_ALREADY_PAID: "ERR_PAYMENT_ALREADY_PAID",
  PAYMENT_REVERT_USED: "ERR_PAYMENT_REVERT_USED",
  ADVANCE_INVALID: "ERR_ADVANCE_INVALID",
  PRICING_NOT_IN_PROJECT: "ERR_PRICING_NOT_IN_PROJECT",
  PRICING_ARCHIVED: "ERR_PRICING_ARCHIVED",
  DEPOSIT_UNAVAILABLE: "ERR_DEPOSIT_UNAVAILABLE",
  FILE_REF_MISSING: "ERR_FILE_REF_MISSING",
  DRIVE_UPLOAD_START_FAILED: "ERR_DRIVE_UPLOAD_START_FAILED",
  DRIVE_UNAVAILABLE: "ERR_DRIVE_UNAVAILABLE",
  PUBLISH_BEFORE_APPROVAL: "ERR_PUBLISH_BEFORE_APPROVAL",
  SCRIPT_COMBO_MISSING: "ERR_SCRIPT_COMBO_MISSING",
  TARGET_PLATFORM_DUPLICATE: "ERR_TARGET_PLATFORM_DUPLICATE",
  ACCOUNT_WRONG_PLATFORM: "ERR_ACCOUNT_WRONG_PLATFORM",
  ACCOUNT_UNAVAILABLE: "ERR_ACCOUNT_UNAVAILABLE",
  CREATOR_NOT_ASSIGNABLE: "ERR_CREATOR_NOT_ASSIGNABLE",
  FORMAT_PLATFORM_MISMATCH: "ERR_FORMAT_PLATFORM_MISMATCH",
  ACCOUNT_NOT_APPROVED_TO_PUBLISH: "ERR_ACCOUNT_NOT_APPROVED_TO_PUBLISH",
  POST_URL_INVALID: "ERR_POST_URL_INVALID",
  POST_URL_WRONG_PLATFORM: "ERR_POST_URL_WRONG_PLATFORM",
  POST_URL_IS_ACCOUNT: "ERR_POST_URL_IS_ACCOUNT",
  POST_URL_MISSING: "ERR_POST_URL_MISSING",
  ACCOUNT_RENAME_LOCKED: "ERR_ACCOUNT_RENAME_LOCKED",
  ACCOUNT_ALREADY_EXISTS: "ERR_ACCOUNT_ALREADY_EXISTS",
  ACCOUNT_IN_USE: "ERR_ACCOUNT_IN_USE",
  CLIP_QUOTA_NOT_VALIDATED: "ERR_CLIP_QUOTA_NOT_VALIDATED",
  CLIP_QUOTA_PHASE_ZERO: "ERR_CLIP_QUOTA_PHASE_ZERO",
  CLIP_QUOTA_REACHED: "ERR_CLIP_QUOTA_REACHED",
  /**
   * Date de publication antérieure à la création de l'assignation. Ce n'est PAS
   * une saisie fautive : c'est une régularisation (post publié hors de l'app).
   * Le client propose de confirmer, il ne bloque pas.
   */
  PUBLISHED_AT_BEFORE_CREATION: "ERR_PUBLISHED_AT_BEFORE_CREATION",
  /** Rôle de portail refusé (talent / clippeur / partenaire selon le contexte). */
  PORTAL_ROLE_REJECTED: "ERR_PORTAL_ROLE_REJECTED",
  /**
   * Droit manquant sur un BLOC du catalogue (convex/permissions.ts). Distinct
   * d'ADMIN_ONLY : celui-ci dit « tu es bien de l'équipe, mais cette case n'est
   * pas cochée pour toi », ce qui appelle une demande à un superadmin, pas une
   * reconnexion. Le bloc manquant voyage en paramètre `permission`.
   */
  PERMISSION_DENIED: "ERR_PERMISSION_DENIED",
  /**
   * Créatrice HORS DU PÉRIMÈTRE du manager (convex/creatorScope.ts). Distinct de
   * PERMISSION_DENIED : le bloc est bien coché, mais pas sur cette personne — la
   * demande à faire n'est pas la même (« ajoute-la à mes créatrices »).
   */
  CREATOR_OUT_OF_SCOPE: "ERR_CREATOR_OUT_OF_SCOPE",
  /**
   * Format dont la GRILLE DE RÉMUNÉRATION n'a jamais été renseignée. Distinct
   * d'une grille volontairement à 0 : ici personne n'a encore décidé combien ce
   * format paie, et assigner figerait un tarif nul dans la mission.
   */
  FORMAT_RATE_NOT_SET: "ERR_FORMAT_RATE_NOT_SET",
  /** Réservé au superadmin — administration des droits, pas travail sur un projet. */
  SUPERADMIN_ONLY: "ERR_SUPERADMIN_ONLY",
  CAMPAIGN_NOT_FOUND: "ERR_CAMPAIGN_NOT_FOUND",
  BRICK_SLOT_NOT_FOUND: "ERR_BRICK_SLOT_NOT_FOUND",
  BRICK_SLOT_WRONG_KIND: "ERR_BRICK_SLOT_WRONG_KIND",
  BRICK_SLOT_DISABLED: "ERR_BRICK_SLOT_DISABLED",
  COMBO_ALREADY_USED: "ERR_COMBO_ALREADY_USED",
  REPLAY_SOURCE_AMBIGUOUS: "ERR_REPLAY_SOURCE_AMBIGUOUS",
  CAMPAIGN_NAME_REQUIRED: "ERR_CAMPAIGN_NAME_REQUIRED",
  NAME_REQUIRED: "ERR_NAME_REQUIRED",
  CAMPAIGN_REFERENCED: "ERR_CAMPAIGN_REFERENCED",
  BRICK_LABEL_REQUIRED: "ERR_BRICK_LABEL_REQUIRED",
  BRICK_NOT_FOUND: "ERR_BRICK_NOT_FOUND",
  LABEL_REQUIRED: "ERR_LABEL_REQUIRED",
  BULK_EMPTY: "ERR_BULK_EMPTY",
  BULK_TOO_MANY: "ERR_BULK_TOO_MANY",
  CAMPAIGN_ARCHIVED: "ERR_CAMPAIGN_ARCHIVED",
  PRICING_REQUIRED: "ERR_PRICING_REQUIRED",
  REPLAY_SOURCE_NOT_FOUND: "ERR_REPLAY_SOURCE_NOT_FOUND",
  REPLAY_SOURCE_REQUIRED: "ERR_REPLAY_SOURCE_REQUIRED",
  REPLAY_SOURCE_NO_SCRIPT: "ERR_REPLAY_SOURCE_NO_SCRIPT",
  NO_COMBO_AVAILABLE: "ERR_NO_COMBO_AVAILABLE",
  TIME_WINDOW_INVALID: "ERR_TIME_WINDOW_INVALID",
  SCRIPT_LOCKED_PUBLISHED: "ERR_SCRIPT_LOCKED_PUBLISHED",
  ASSIGNMENT_NOT_SCRIPT: "ERR_ASSIGNMENT_NOT_SCRIPT",
  BRICK_NOT_IN_CAMPAIGN: "ERR_BRICK_NOT_IN_CAMPAIGN",
  BRICK_WRONG_SLOT: "ERR_BRICK_WRONG_SLOT",
  BRICK_DISABLED: "ERR_BRICK_DISABLED",
  COMBO_BRICK_NOT_FOUND: "ERR_COMBO_BRICK_NOT_FOUND",
  BRICK_TEXT_REQUIRED: "ERR_BRICK_TEXT_REQUIRED",
  BRICK_TEXT_TOO_LONG: "ERR_BRICK_TEXT_TOO_LONG",
  SOURCE_BRICK_NOT_FOUND: "ERR_SOURCE_BRICK_NOT_FOUND",
  RUSH_NOT_IN_PROJECT: "ERR_RUSH_NOT_IN_PROJECT",
  RUSH_NOT_ASSIGNABLE: "ERR_RUSH_NOT_ASSIGNABLE",
  TALENT_NOT_IN_PROJECT: "ERR_TALENT_NOT_IN_PROJECT",
  TALENT_NOT_PAIRED: "ERR_TALENT_NOT_PAIRED",
  CLIPPER_NOT_IN_PROJECT: "ERR_CLIPPER_NOT_IN_PROJECT",
  CLIPPER_NO_LONGER: "ERR_CLIPPER_NO_LONGER",
  CLIPPER_NOT_ASSIGNABLE: "ERR_CLIPPER_NOT_ASSIGNABLE",
  PUBLISH_ACCOUNT_REQUIRED: "ERR_PUBLISH_ACCOUNT_REQUIRED",
  ALL_SCRIPTS_USED: "ERR_ALL_SCRIPTS_USED",
  HOOK_NOT_FOUND: "ERR_HOOK_NOT_FOUND",
  ONLY_HOOK_GRADUATES: "ERR_ONLY_HOOK_GRADUATES",
  PROVEN_CAMPAIGN_MISSING: "ERR_PROVEN_CAMPAIGN_MISSING",
  HOOK_ALREADY_PROVEN: "ERR_HOOK_ALREADY_PROVEN",
  COMBO_IN_COOLDOWN: "ERR_COMBO_IN_COOLDOWN",
  NO_SCRIPT_FREE_THAT_DAY: "ERR_NO_SCRIPT_FREE_THAT_DAY",
  MODEL_VIDEO_URL_INVALID: "ERR_MODEL_VIDEO_URL_INVALID",
  MODEL_VIDEOS_TOO_MANY: "ERR_MODEL_VIDEOS_TOO_MANY",
  ASSIGNMENT_DELETE_LOCKED: "ERR_ASSIGNMENT_DELETE_LOCKED",
  VIDEO_NOT_IN_REVIEW_APPROVE: "ERR_VIDEO_NOT_IN_REVIEW_APPROVE",
  VIDEO_NOT_IN_REVIEW_REJECT: "ERR_VIDEO_NOT_IN_REVIEW_REJECT",
  REJECTION_REASON_REQUIRED: "ERR_REJECTION_REASON_REQUIRED",
  MISSION_NOT_FOUND: "ERR_MISSION_NOT_FOUND",
  MISSION_NOT_WAITING_CREATOR: "ERR_MISSION_NOT_WAITING_CREATOR",
  BONUS_NEEDS_PUBLISHED: "ERR_BONUS_NEEDS_PUBLISHED",
  BONUS_IS_AUTOMATIC: "ERR_BONUS_IS_AUTOMATIC",
  BONUS_NO_PUBLICATION: "ERR_BONUS_NO_PUBLICATION",
  VIEW_COUNT_INVALID: "ERR_VIEW_COUNT_INVALID",
  CREATOR_NAME_REQUIRED: "ERR_CREATOR_NAME_REQUIRED",
  EMAIL_INVALID: "ERR_EMAIL_INVALID",
  CREATOR_EMAIL_TAKEN: "ERR_CREATOR_EMAIL_TAKEN",
  INVITATION_ALREADY_ACCEPTED: "ERR_INVITATION_ALREADY_ACCEPTED",
  TIMEZONE_UNKNOWN: "ERR_TIMEZONE_UNKNOWN",
  ONLY_TALENT_PAIRS: "ERR_ONLY_TALENT_PAIRS",
  NOT_A_CLIPPER: "ERR_NOT_A_CLIPPER",
  BONUS_PRICING_NOT_FOUND: "ERR_BONUS_PRICING_NOT_FOUND",
  RATE_INVALID: "ERR_RATE_INVALID",
  CREATOR_ACCOUNT_NOT_FOUND: "ERR_CREATOR_ACCOUNT_NOT_FOUND",
  NOT_A_CREATOR_ACCOUNT: "ERR_NOT_A_CREATOR_ACCOUNT",
  CREATOR_ALREADY_IN_PROJECT: "ERR_CREATOR_ALREADY_IN_PROJECT",
  REF_TAKEN_BY_CREATOR: "ERR_REF_TAKEN_BY_CREATOR",
  REF_TAKEN_BY_INFLUENCER: "ERR_REF_TAKEN_BY_INFLUENCER",
  REWARD_CASH_INVALID: "ERR_REWARD_CASH_INVALID",
  REWARD_KIND_INVALID: "ERR_REWARD_KIND_INVALID",
  REWARD_REAL_COST_INVALID: "ERR_REWARD_REAL_COST_INVALID",
  WINNER_COUNT_INVALID: "ERR_WINNER_COUNT_INVALID",
  CHALLENGE_NAME_REQUIRED: "ERR_CHALLENGE_NAME_REQUIRED",
  CHALLENGE_NAME_TOO_LONG: "ERR_CHALLENGE_NAME_TOO_LONG",
  TARGET_VIEWS_INVALID: "ERR_TARGET_VIEWS_INVALID",
  DEADLINE_INVALID: "ERR_DEADLINE_INVALID",
  DEADLINE_IN_PAST: "ERR_DEADLINE_IN_PAST",
  CHALLENGE_SCRIPT_TOO_LONG: "ERR_CHALLENGE_SCRIPT_TOO_LONG",
  DEADLINE_ONLY_EXTENDS: "ERR_DEADLINE_ONLY_EXTENDS",
  CHALLENGE_CLOSED_FOREVER: "ERR_CHALLENGE_CLOSED_FOREVER",
  CHALLENGE_NEEDS_PARTICIPANT: "ERR_CHALLENGE_NEEDS_PARTICIPANT",
  CHALLENGE_DEADLINE_PASSED: "ERR_CHALLENGE_DEADLINE_PASSED",
  CHALLENGE_PARTNER_ONLY: "ERR_CHALLENGE_PARTNER_ONLY",
  CHALLENGE_CREATOR_NOT_JOINED: "ERR_CHALLENGE_CREATOR_NOT_JOINED",
  CHALLENGE_PARTICIPANT_LOCKED: "ERR_CHALLENGE_PARTICIPANT_LOCKED",
  VIDEO_NOT_IN_CHALLENGE: "ERR_VIDEO_NOT_IN_CHALLENGE",
  FOLDER_NAME_REQUIRED: "ERR_FOLDER_NAME_REQUIRED",
  FOLDER_NAME_TOO_LONG: "ERR_FOLDER_NAME_TOO_LONG",
  FOLDER_ALREADY_EXISTS: "ERR_FOLDER_ALREADY_EXISTS",
  FOLDER_NOT_FOUND: "ERR_FOLDER_NOT_FOUND",
  ASSET_FILE_REJECTED: "ERR_ASSET_FILE_REJECTED",
  WARMUP_DATE_NEEDS_WARMUP: "ERR_WARMUP_DATE_NEEDS_WARMUP",
  WARMUP_DURATION_INVALID: "ERR_WARMUP_DURATION_INVALID",
  CHALLENGE_WIN_NOT_FOUND: "ERR_CHALLENGE_WIN_NOT_FOUND",
  CANCEL_REASON_REQUIRED: "ERR_CANCEL_REASON_REQUIRED",
  URL_REQUIRED: "ERR_URL_REQUIRED",
  URL_CANNOT_BE_EMPTY: "ERR_URL_CANNOT_BE_EMPTY",
  INSPIRATION_NOT_FOUND: "ERR_INSPIRATION_NOT_FOUND",
  FOLDER_NAME_TOO_LONG_CHARS: "ERR_FOLDER_NAME_TOO_LONG_CHARS",
  RADAR_ACCOUNT_NOT_FOUND: "ERR_RADAR_ACCOUNT_NOT_FOUND",
  RADAR_HANDLE_INVALID: "ERR_RADAR_HANDLE_INVALID",
  RADAR_ACCOUNT_ALREADY_FOLLOWED: "ERR_RADAR_ACCOUNT_ALREADY_FOLLOWED",
  SEARCH_KEYWORD_REQUIRED: "ERR_SEARCH_KEYWORD_REQUIRED",
  RUSH_NOT_REJECTABLE: "ERR_RUSH_NOT_REJECTABLE",
  REJECTION_REASON_TOO_LONG: "ERR_REJECTION_REASON_TOO_LONG",
  PERSON_NAMES_REQUIRED: "ERR_PERSON_NAMES_REQUIRED",
  PERSON_NAMES_TOO_LONG: "ERR_PERSON_NAMES_TOO_LONG",
  PERSON_ALREADY_EXISTS: "ERR_PERSON_ALREADY_EXISTS",
  PERSON_NOT_FOUND: "ERR_PERSON_NOT_FOUND",
  CONTRACT_FILE_REJECTED: "ERR_CONTRACT_FILE_REJECTED",
  CONTRACT_NOT_FOUND: "ERR_CONTRACT_NOT_FOUND",
  MODULE_TITLE_REQUIRED: "ERR_MODULE_TITLE_REQUIRED",
  MODULE_TITLE_TOO_LONG: "ERR_MODULE_TITLE_TOO_LONG",
  MODULE_CONTENT_TOO_LONG: "ERR_MODULE_CONTENT_TOO_LONG",
  MODULE_LOCALE_UNKNOWN: "ERR_MODULE_LOCALE_UNKNOWN",
  MODULE_NOT_FOUND: "ERR_MODULE_NOT_FOUND",
  ICP_NAME_REQUIRED: "ERR_ICP_NAME_REQUIRED",
  ICP_NAME_TOO_LONG: "ERR_ICP_NAME_TOO_LONG",
  ICP_ALREADY_EXISTS: "ERR_ICP_ALREADY_EXISTS",
  ICP_NOT_FOUND: "ERR_ICP_NOT_FOUND",
  FORMAT_BASE_RATE_INVALID: "ERR_FORMAT_BASE_RATE_INVALID",
  FORMAT_VIEW_BONUS_INVALID: "ERR_FORMAT_VIEW_BONUS_INVALID",
  FORMAT_TIERS_INVALID: "ERR_FORMAT_TIERS_INVALID",
  FORMAT_NAME_REQUIRED: "ERR_FORMAT_NAME_REQUIRED",
  FORMAT_NOT_IN_PROJECT: "ERR_FORMAT_NOT_IN_PROJECT",
  PROJECT_NAME_REQUIRED: "ERR_PROJECT_NAME_REQUIRED",
  SLUG_INVALID: "ERR_SLUG_INVALID",
  SLUG_RESERVED: "ERR_SLUG_RESERVED",
  SLUG_TAKEN: "ERR_SLUG_TAKEN",
  PAYOUT_DAY_INVALID: "ERR_PAYOUT_DAY_INVALID",
  WARMUP_DAYS_INVALID: "ERR_WARMUP_DAYS_INVALID",
  CAROUSEL_FIELDS_REQUIRED: "ERR_CAROUSEL_FIELDS_REQUIRED",
  SCREENREC_TITLE_REQUIRED: "ERR_SCREENREC_TITLE_REQUIRED",
  SCREENREC_IMAGE_REQUIRED: "ERR_SCREENREC_IMAGE_REQUIRED",
  SCREENREC_DEVICE_REQUIRED: "ERR_SCREENREC_DEVICE_REQUIRED",
  SCREENREC_REPACK_REQUIRED: "ERR_SCREENREC_REPACK_REQUIRED",
  ICP_REQUIRED_FOR_SHORT: "ERR_ICP_REQUIRED_FOR_SHORT",
  SOURCE_ID_INVALID: "ERR_SOURCE_ID_INVALID",
  SHORT_ALREADY_ON_TIKTOK: "ERR_SHORT_ALREADY_ON_TIKTOK",
  SHORT_ALREADY_ON_PLATFORM: "ERR_SHORT_ALREADY_ON_PLATFORM",
  MEDIA_TYPE_NOT_ALLOWED: "ERR_MEDIA_TYPE_NOT_ALLOWED",
  PUBLICATION_NOT_FOUND: "ERR_PUBLICATION_NOT_FOUND",
  ACCOUNT_EDIT_AFTER_PUBLISH: "ERR_ACCOUNT_EDIT_AFTER_PUBLISH",
  ACCOUNT_EDIT_ONCE: "ERR_ACCOUNT_EDIT_ONCE",
  ACCOUNT_NOT_ON_PLATFORM: "ERR_ACCOUNT_NOT_ON_PLATFORM",
  CAROUSEL_PARTLY_PUBLISHED: "ERR_CAROUSEL_PARTLY_PUBLISHED",
  SNAPSHOT_BEFORE_PUBLICATION: "ERR_SNAPSHOT_BEFORE_PUBLICATION",
  SNAPSHOT_NOT_FOUND: "ERR_SNAPSHOT_NOT_FOUND",
  PRICING_NAME_REQUIRED: "ERR_PRICING_NAME_REQUIRED",
  PRICING_TARGET_VIDEOS_INVALID: "ERR_PRICING_TARGET_VIDEOS_INVALID",
  PRICING_FIELD_INVALID: "ERR_PRICING_FIELD_INVALID",
  PRICING_VIEW_THRESHOLD_INVALID: "ERR_PRICING_VIEW_THRESHOLD_INVALID",
  TIER_THRESHOLD_INVALID: "ERR_TIER_THRESHOLD_INVALID",
  TIER_CASH_INVALID: "ERR_TIER_CASH_INVALID",
  TIER_KIND_LABEL_REQUIRED: "ERR_TIER_KIND_LABEL_REQUIRED",
  TIER_REAL_COST_INVALID: "ERR_TIER_REAL_COST_INVALID",
  TIER_REAL_COST_KIND_ONLY: "ERR_TIER_REAL_COST_KIND_ONLY",
  TEMPLATE_NAME_REQUIRED: "ERR_TEMPLATE_NAME_REQUIRED",
  TEMPLATE_NEEDS_TIER: "ERR_TEMPLATE_NEEDS_TIER",
  TEMPLATE_TIER_DUPLICATE: "ERR_TEMPLATE_TIER_DUPLICATE",
  ACCOUNT_NOT_FINALIZED: "ERR_ACCOUNT_NOT_FINALIZED",
  LOGIN_ACCOUNT_NOT_FOUND: "ERR_LOGIN_ACCOUNT_NOT_FOUND",
  RESET_FORBIDDEN_SUPERADMIN: "ERR_RESET_FORBIDDEN_SUPERADMIN",
  BRICK_NOT_RUSH_ELIGIBLE: "ERR_BRICK_NOT_RUSH_ELIGIBLE",
  NO_ELIGIBLE_COMBO: "ERR_NO_ELIGIBLE_COMBO",
  NO_ACTIVE_HOOK_OR_BODY: "ERR_NO_ACTIVE_HOOK_OR_BODY",
  ACCOUNT_RENAME_COLLISION: "ERR_ACCOUNT_RENAME_COLLISION",
  ASSIGNMENT_CANCEL_LOCKED: "ERR_ASSIGNMENT_CANCEL_LOCKED",
  PAY_CYCLE_LOCKED: "ERR_PAY_CYCLE_LOCKED",
  SPARK_AD_DATE_INVALID: "ERR_SPARK_AD_DATE_INVALID",
  POPULATION_LOCKED: "ERR_POPULATION_LOCKED",
  CHALLENGE_BRICK_NOT_FOUND: "ERR_CHALLENGE_BRICK_NOT_FOUND",
  CHALLENGE_NOT_FOUND: "ERR_CHALLENGE_NOT_FOUND",
  CHALLENGE_PRICING_FIXED_NOT_ZERO: "ERR_CHALLENGE_PRICING_FIXED_NOT_ZERO",
  CHALLENGE_TERMS_LOCKED: "ERR_CHALLENGE_TERMS_LOCKED",
  CHALLENGE_DELETE_LOCKED: "ERR_CHALLENGE_DELETE_LOCKED",
  CHALLENGE_NOT_OPEN_YET: "ERR_CHALLENGE_NOT_OPEN_YET",
  CHALLENGE_CLOSED: "ERR_CHALLENGE_CLOSED",
  CHALLENGE_DEADLINE_OVER: "ERR_CHALLENGE_DEADLINE_OVER",
  CHALLENGE_NOT_PARTICIPANT: "ERR_CHALLENGE_NOT_PARTICIPANT",
  CHALLENGE_NO_SCRIPT: "ERR_CHALLENGE_NO_SCRIPT",
  CHALLENGE_WIN_PAID: "ERR_CHALLENGE_WIN_PAID",
  FORMAT_REFERENCED: "ERR_FORMAT_REFERENCED",
  COOLDOWN_DAYS_INVALID: "ERR_COOLDOWN_DAYS_INVALID",
  SHARE_NO_BLOCK: "ERR_SHARE_NO_BLOCK",
  SHARE_PERIOD_INVALID: "ERR_SHARE_PERIOD_INVALID",
  SHARE_CREATOR_REQUIRED: "ERR_SHARE_CREATOR_REQUIRED",
  SHARE_NAME_INVALID: "ERR_SHARE_NAME_INVALID",
  SHARE_EXPIRY_INVALID: "ERR_SHARE_EXPIRY_INVALID",
  SHARE_CAMPAIGN_NOT_IN_PROJECT: "ERR_SHARE_CAMPAIGN_NOT_IN_PROJECT",
  SHARE_NOT_FOUND: "ERR_SHARE_NOT_FOUND",
} as const;

export type ErrCode = (typeof ERR)[keyof typeof ERR];

/** Paramètres d'interpolation, transportés jusqu'au client qui rend la phrase. */
export type ErrParams = Record<string, string | number>;

/**
 * Construit un rejet métier STRUCTURÉ. Le `message` français reste dans la
 * charge : il sert de repli d'affichage (et de trace lisible dans les logs)
 * quand le client ne connaît pas le code.
 */
export function err(
  code: ErrCode,
  message: string,
  params?: ErrParams,
): ConvexError<{ code: string; message: string; params?: ErrParams }> {
  return new ConvexError(
    params === undefined ? { code, message } : { code, message, params },
  );
}

/**
 * Message LISIBLE d'une erreur, pour les harnais e2e et les rapports de
 * migration.
 *
 * Une `ConvexError` transporte désormais soit une chaîne (forme historique),
 * soit une charge STRUCTURÉE `{ code, message }` (cf convex/errorCodes.ts).
 * `String(e.data)` rendait « [object Object] » sur la seconde — ce qui a fait
 * tomber cinq specs e2e d'un coup, toutes en assertant du texte français.
 */
export function convexErrorText(e: unknown): string {
  if (!(e instanceof ConvexError)) return "error";
  const d = e.data;
  if (d !== null && typeof d === "object" && "message" in d) {
    const p = d as { code?: unknown; message?: unknown };
    // Le CODE est concaténé : une assertion e2e peut alors porter sur lui
    // plutôt que sur la formulation, qui elle peut être traduite.
    return typeof p.code === "string"
      ? `${p.code} ${String(p.message)}`
      : String(p.message);
  }
  return String(d);
}
