/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as abAttribution from "../abAttribution.js";
import type * as abOffers from "../abOffers.js";
import type * as abPurchases from "../abPurchases.js";
import type * as accountPhase from "../accountPhase.js";
import type * as accountValidation from "../accountValidation.js";
import type * as adminRecovery from "../adminRecovery.js";
import type * as analyticsContract from "../analyticsContract.js";
import type * as analyticsDates from "../analyticsDates.js";
import type * as analyticsHub from "../analyticsHub.js";
import type * as analyticsHubMath from "../analyticsHubMath.js";
import type * as analyticsWindowed from "../analyticsWindowed.js";
import type * as apifyApi from "../apifyApi.js";
import type * as apifyItem from "../apifyItem.js";
import type * as apifySync from "../apifySync.js";
import type * as assets from "../assets.js";
import type * as assetsMigration from "../assetsMigration.js";
import type * as assignments from "../assignments.js";
import type * as attributionWindow from "../attributionWindow.js";
import type * as auth from "../auth.js";
import type * as bootstrap from "../bootstrap.js";
import type * as calendarStatus from "../calendarStatus.js";
import type * as challengePortal from "../challengePortal.js";
import type * as challengeScore from "../challengeScore.js";
import type * as challengeSync from "../challengeSync.js";
import type * as challenges from "../challenges.js";
import type * as changedFields from "../changedFields.js";
import type * as churn from "../churn.js";
import type * as clipQuota from "../clipQuota.js";
import type * as clipperAssignmentFields from "../clipperAssignmentFields.js";
import type * as clipperReadiness from "../clipperReadiness.js";
import type * as cloudflareStream from "../cloudflareStream.js";
import type * as cloudflareStreamApi from "../cloudflareStreamApi.js";
import type * as coherenceInputs from "../coherenceInputs.js";
import type * as collectAvailability from "../collectAvailability.js";
import type * as comboCooldown from "../comboCooldown.js";
import type * as comboFreeing from "../comboFreeing.js";
import type * as compta from "../compta.js";
import type * as comptaMath from "../comptaMath.js";
import type * as compteAvatar from "../compteAvatar.js";
import type * as compteStatut from "../compteStatut.js";
import type * as comptes from "../comptes.js";
import type * as conversionAttribution from "../conversionAttribution.js";
import type * as conversionSync from "../conversionSync.js";
import type * as countries from "../countries.js";
import type * as creatorActivation from "../creatorActivation.js";
import type * as creatorActivity from "../creatorActivity.js";
import type * as creatorAssignmentFields from "../creatorAssignmentFields.js";
import type * as creatorAvatar from "../creatorAvatar.js";
import type * as creatorContracts from "../creatorContracts.js";
import type * as creatorDay from "../creatorDay.js";
import type * as creatorPricing from "../creatorPricing.js";
import type * as creatorScope from "../creatorScope.js";
import type * as creatorTimezone from "../creatorTimezone.js";
import type * as creatorVideos from "../creatorVideos.js";
import type * as creators from "../creators.js";
import type * as crons from "../crons.js";
import type * as currencyRate from "../currencyRate.js";
import type * as dashboard from "../dashboard.js";
import type * as dashboardActions from "../dashboardActions.js";
import type * as dashboardCache from "../dashboardCache.js";
import type * as dashboardDecisions from "../dashboardDecisions.js";
import type * as dateFr from "../dateFr.js";
import type * as decisionThresholds from "../decisionThresholds.js";
import type * as decisions from "../decisions.js";
import type * as demoMultiProject from "../demoMultiProject.js";
import type * as demoSeed from "../demoSeed.js";
import type * as earlyReadings from "../earlyReadings.js";
import type * as earlyTracking from "../earlyTracking.js";
import type * as emailApi from "../emailApi.js";
import type * as emailMessages from "../emailMessages.js";
import type * as emails from "../emails.js";
import type * as errorCodes from "../errorCodes.js";
import type * as experienceStats from "../experienceStats.js";
import type * as facebookApify from "../facebookApify.js";
import type * as fileDrop from "../fileDrop.js";
import type * as filterPresets from "../filterPresets.js";
import type * as folders from "../folders.js";
import type * as formats from "../formats.js";
import type * as functions from "../functions.js";
import type * as googleDriveApi from "../googleDriveApi.js";
import type * as graduation from "../graduation.js";
import type * as guide from "../guide.js";
import type * as guideFrFixes from "../guideFrFixes.js";
import type * as guideModuleLocale from "../guideModuleLocale.js";
import type * as guideModules from "../guideModules.js";
import type * as guideModulesEn from "../guideModulesEn.js";
import type * as guideModulesEs from "../guideModulesEs.js";
import type * as guideModulesPt from "../guideModulesPt.js";
import type * as handleHygiene from "../handleHygiene.js";
import type * as hogWindow from "../hogWindow.js";
import type * as hookAvailability from "../hookAvailability.js";
import type * as hooks from "../hooks.js";
import type * as http from "../http.js";
import type * as i18n from "../i18n.js";
import type * as icps from "../icps.js";
import type * as inspirationThumbnails from "../inspirationThumbnails.js";
import type * as inspirations from "../inspirations.js";
import type * as internalAccounts from "../internalAccounts.js";
import type * as leaderboardCache from "../leaderboardCache.js";
import type * as likesNegativeMigration from "../likesNegativeMigration.js";
import type * as locales from "../locales.js";
import type * as maintenance from "../maintenance.js";
import type * as managerCpm from "../managerCpm.js";
import type * as managerPay from "../managerPay.js";
import type * as marketAggregate from "../marketAggregate.js";
import type * as marketCost from "../marketCost.js";
import type * as marketDecision from "../marketDecision.js";
import type * as marketDerive from "../marketDerive.js";
import type * as marketGroups from "../marketGroups.js";
import type * as marketMoney from "../marketMoney.js";
import type * as marketPnl from "../marketPnl.js";
import type * as marketPromo from "../marketPromo.js";
import type * as marketValue from "../marketValue.js";
import type * as marketWindow from "../marketWindow.js";
import type * as mcpAnnulation from "../mcpAnnulation.js";
import type * as mcpDefaire from "../mcpDefaire.js";
import type * as mcpExperiences from "../mcpExperiences.js";
import type * as mcpFormat from "../mcpFormat.js";
import type * as mcpHttp from "../mcpHttp.js";
import type * as mcpOAuth from "../mcpOAuth.js";
import type * as mcpOAuthCore from "../mcpOAuthCore.js";
import type * as mcpOAuthHttp from "../mcpOAuthHttp.js";
import type * as mcpPrompts from "../mcpPrompts.js";
import type * as mcpPropositions from "../mcpPropositions.js";
import type * as mcpProtocol from "../mcpProtocol.js";
import type * as mcpTokens from "../mcpTokens.js";
import type * as mcpTools from "../mcpTools.js";
import type * as mcpVideo from "../mcpVideo.js";
import type * as mcpWriteArgs from "../mcpWriteArgs.js";
import type * as mcpWriteCommon from "../mcpWriteCommon.js";
import type * as mcpWriteDomains from "../mcpWriteDomains.js";
import type * as mcpWrites from "../mcpWrites.js";
import type * as mcpWritesMissions from "../mcpWritesMissions.js";
import type * as mcpWritesPublications from "../mcpWritesPublications.js";
import type * as mcpWritesScripts from "../mcpWritesScripts.js";
import type * as mcpWritesVeille from "../mcpWritesVeille.js";
import type * as memberPermissions from "../memberPermissions.js";
import type * as metricSnapshots from "../metricSnapshots.js";
import type * as metricsDisplay from "../metricsDisplay.js";
import type * as migrations from "../migrations.js";
import type * as modelVideoEmbeds from "../modelVideoEmbeds.js";
import type * as moneyFormat from "../moneyFormat.js";
import type * as nightlyViewsSync from "../nightlyViewsSync.js";
import type * as notificationEvents from "../notificationEvents.js";
import type * as notificationMessage from "../notificationMessage.js";
import type * as notificationWindow from "../notificationWindow.js";
import type * as notifications from "../notifications.js";
import type * as notifyApi from "../notifyApi.js";
import type * as opsDigest from "../opsDigest.js";
import type * as passwordReset from "../passwordReset.js";
import type * as payCycle from "../payCycle.js";
import type * as payWindow from "../payWindow.js";
import type * as payments from "../payments.js";
import type * as paymentsView from "../paymentsView.js";
import type * as permissionCoverage from "../permissionCoverage.js";
import type * as permissionProbe from "../permissionProbe.js";
import type * as permissions from "../permissions.js";
import type * as personnes from "../personnes.js";
import type * as platforms from "../platforms.js";
import type * as postUrlDate from "../postUrlDate.js";
import type * as postUrlResolution from "../postUrlResolution.js";
import type * as postUrlShape from "../postUrlShape.js";
import type * as postWindow from "../postWindow.js";
import type * as posthogApi from "../posthogApi.js";
import type * as posthogSync from "../posthogSync.js";
import type * as pricing from "../pricing.js";
import type * as pricingSnapshotMigration from "../pricingSnapshotMigration.js";
import type * as profitability from "../profitability.js";
import type * as profitabilityMath from "../profitabilityMath.js";
import type * as progression from "../progression.js";
import type * as projectLifecycle from "../projectLifecycle.js";
import type * as projectLifecycleRules from "../projectLifecycleRules.js";
import type * as projectPurgeTables from "../projectPurgeTables.js";
import type * as projects from "../projects.js";
import type * as provisionAdmin from "../provisionAdmin.js";
import type * as publicShare from "../publicShare.js";
import type * as publicShares from "../publicShares.js";
import type * as publicationLateness from "../publicationLateness.js";
import type * as publications from "../publications.js";
import type * as quadrant from "../quadrant.js";
import type * as quadrantSettings from "../quadrantSettings.js";
import type * as quadrantSync from "../quadrantSync.js";
import type * as radar from "../radar.js";
import type * as radarApi from "../radarApi.js";
import type * as reminderGrouping from "../reminderGrouping.js";
import type * as remunerate from "../remunerate.js";
import type * as retentionCost from "../retentionCost.js";
import type * as reviewQueue from "../reviewQueue.js";
import type * as roles from "../roles.js";
import type * as rushScriptEligibility from "../rushScriptEligibility.js";
import type * as rushStatus from "../rushStatus.js";
import type * as rushes from "../rushes.js";
import type * as scriptAnalytics from "../scriptAnalytics.js";
import type * as scriptDecision from "../scriptDecision.js";
import type * as scriptNotif from "../scriptNotif.js";
import type * as scriptSeedData from "../scriptSeedData.js";
import type * as scriptZonesSetting from "../scriptZonesSetting.js";
import type * as scripts from "../scripts.js";
import type * as segmentFunnel from "../segmentFunnel.js";
import type * as settledCycles from "../settledCycles.js";
import type * as showcase from "../showcase.js";
import type * as snapchatInternal from "../snapchatInternal.js";
import type * as snapchatPostUrl from "../snapchatPostUrl.js";
import type * as snapchatPublicPage from "../snapchatPublicPage.js";
import type * as snapshotMatching from "../snapshotMatching.js";
import type * as snytchDrive from "../snytchDrive.js";
import type * as soloDays from "../soloDays.js";
import type * as storage from "../storage.js";
import type * as storageCleanup from "../storageCleanup.js";
import type * as syncScope from "../syncScope.js";
import type * as talentBriefFields from "../talentBriefFields.js";
import type * as talentPay from "../talentPay.js";
import type * as talentRetainer from "../talentRetainer.js";
import type * as talentRushFields from "../talentRushFields.js";
import type * as targetAccountSwap from "../targetAccountSwap.js";
import type * as team from "../team.js";
import type * as tiktokInternal from "../tiktokInternal.js";
import type * as tiktokPublicPage from "../tiktokPublicPage.js";
import type * as trackerData from "../trackerData.js";
import type * as unitEconomics from "../unitEconomics.js";
import type * as viewCounters from "../viewCounters.js";
import type * as viewsDaily from "../viewsDaily.js";
import type * as viewsPulse from "../viewsPulse.js";
import type * as viewsPulseCore from "../viewsPulseCore.js";
import type * as warmup from "../warmup.js";
import type * as warmupGuideFused from "../warmupGuideFused.js";
import type * as warmupMode from "../warmupMode.js";
import type * as whopApi from "../whopApi.js";
import type * as whopClients from "../whopClients.js";
import type * as whopLedgerApi from "../whopLedgerApi.js";
import type * as whopNotifyTriggers from "../whopNotifyTriggers.js";
import type * as whopPaymentsAccess from "../whopPaymentsAccess.js";
import type * as whopRevenue from "../whopRevenue.js";
import type * as whopSync from "../whopSync.js";
import type * as windowCacheTtl from "../windowCacheTtl.js";
import type * as youtubeApi from "../youtubeApi.js";
import type * as youtubeChannel from "../youtubeChannel.js";
import type * as youtubeSync from "../youtubeSync.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const fullApi: ApiFromModules<{
  abAttribution: typeof abAttribution;
  abOffers: typeof abOffers;
  abPurchases: typeof abPurchases;
  accountPhase: typeof accountPhase;
  accountValidation: typeof accountValidation;
  adminRecovery: typeof adminRecovery;
  analyticsContract: typeof analyticsContract;
  analyticsDates: typeof analyticsDates;
  analyticsHub: typeof analyticsHub;
  analyticsHubMath: typeof analyticsHubMath;
  analyticsWindowed: typeof analyticsWindowed;
  apifyApi: typeof apifyApi;
  apifyItem: typeof apifyItem;
  apifySync: typeof apifySync;
  assets: typeof assets;
  assetsMigration: typeof assetsMigration;
  assignments: typeof assignments;
  attributionWindow: typeof attributionWindow;
  auth: typeof auth;
  bootstrap: typeof bootstrap;
  calendarStatus: typeof calendarStatus;
  challengePortal: typeof challengePortal;
  challengeScore: typeof challengeScore;
  challengeSync: typeof challengeSync;
  challenges: typeof challenges;
  changedFields: typeof changedFields;
  churn: typeof churn;
  clipQuota: typeof clipQuota;
  clipperAssignmentFields: typeof clipperAssignmentFields;
  clipperReadiness: typeof clipperReadiness;
  cloudflareStream: typeof cloudflareStream;
  cloudflareStreamApi: typeof cloudflareStreamApi;
  coherenceInputs: typeof coherenceInputs;
  collectAvailability: typeof collectAvailability;
  comboCooldown: typeof comboCooldown;
  comboFreeing: typeof comboFreeing;
  compta: typeof compta;
  comptaMath: typeof comptaMath;
  compteAvatar: typeof compteAvatar;
  compteStatut: typeof compteStatut;
  comptes: typeof comptes;
  conversionAttribution: typeof conversionAttribution;
  conversionSync: typeof conversionSync;
  countries: typeof countries;
  creatorActivation: typeof creatorActivation;
  creatorActivity: typeof creatorActivity;
  creatorAssignmentFields: typeof creatorAssignmentFields;
  creatorAvatar: typeof creatorAvatar;
  creatorContracts: typeof creatorContracts;
  creatorDay: typeof creatorDay;
  creatorPricing: typeof creatorPricing;
  creatorScope: typeof creatorScope;
  creatorTimezone: typeof creatorTimezone;
  creatorVideos: typeof creatorVideos;
  creators: typeof creators;
  crons: typeof crons;
  currencyRate: typeof currencyRate;
  dashboard: typeof dashboard;
  dashboardActions: typeof dashboardActions;
  dashboardCache: typeof dashboardCache;
  dashboardDecisions: typeof dashboardDecisions;
  dateFr: typeof dateFr;
  decisionThresholds: typeof decisionThresholds;
  decisions: typeof decisions;
  demoMultiProject: typeof demoMultiProject;
  demoSeed: typeof demoSeed;
  earlyReadings: typeof earlyReadings;
  earlyTracking: typeof earlyTracking;
  emailApi: typeof emailApi;
  emailMessages: typeof emailMessages;
  emails: typeof emails;
  errorCodes: typeof errorCodes;
  experienceStats: typeof experienceStats;
  facebookApify: typeof facebookApify;
  fileDrop: typeof fileDrop;
  filterPresets: typeof filterPresets;
  folders: typeof folders;
  formats: typeof formats;
  functions: typeof functions;
  googleDriveApi: typeof googleDriveApi;
  graduation: typeof graduation;
  guide: typeof guide;
  guideFrFixes: typeof guideFrFixes;
  guideModuleLocale: typeof guideModuleLocale;
  guideModules: typeof guideModules;
  guideModulesEn: typeof guideModulesEn;
  guideModulesEs: typeof guideModulesEs;
  guideModulesPt: typeof guideModulesPt;
  handleHygiene: typeof handleHygiene;
  hogWindow: typeof hogWindow;
  hookAvailability: typeof hookAvailability;
  hooks: typeof hooks;
  http: typeof http;
  i18n: typeof i18n;
  icps: typeof icps;
  inspirationThumbnails: typeof inspirationThumbnails;
  inspirations: typeof inspirations;
  internalAccounts: typeof internalAccounts;
  leaderboardCache: typeof leaderboardCache;
  likesNegativeMigration: typeof likesNegativeMigration;
  locales: typeof locales;
  maintenance: typeof maintenance;
  managerCpm: typeof managerCpm;
  managerPay: typeof managerPay;
  marketAggregate: typeof marketAggregate;
  marketCost: typeof marketCost;
  marketDecision: typeof marketDecision;
  marketDerive: typeof marketDerive;
  marketGroups: typeof marketGroups;
  marketMoney: typeof marketMoney;
  marketPnl: typeof marketPnl;
  marketPromo: typeof marketPromo;
  marketValue: typeof marketValue;
  marketWindow: typeof marketWindow;
  mcpAnnulation: typeof mcpAnnulation;
  mcpDefaire: typeof mcpDefaire;
  mcpExperiences: typeof mcpExperiences;
  mcpFormat: typeof mcpFormat;
  mcpHttp: typeof mcpHttp;
  mcpOAuth: typeof mcpOAuth;
  mcpOAuthCore: typeof mcpOAuthCore;
  mcpOAuthHttp: typeof mcpOAuthHttp;
  mcpPrompts: typeof mcpPrompts;
  mcpPropositions: typeof mcpPropositions;
  mcpProtocol: typeof mcpProtocol;
  mcpTokens: typeof mcpTokens;
  mcpTools: typeof mcpTools;
  mcpVideo: typeof mcpVideo;
  mcpWriteArgs: typeof mcpWriteArgs;
  mcpWriteCommon: typeof mcpWriteCommon;
  mcpWriteDomains: typeof mcpWriteDomains;
  mcpWrites: typeof mcpWrites;
  mcpWritesMissions: typeof mcpWritesMissions;
  mcpWritesPublications: typeof mcpWritesPublications;
  mcpWritesScripts: typeof mcpWritesScripts;
  mcpWritesVeille: typeof mcpWritesVeille;
  memberPermissions: typeof memberPermissions;
  metricSnapshots: typeof metricSnapshots;
  metricsDisplay: typeof metricsDisplay;
  migrations: typeof migrations;
  modelVideoEmbeds: typeof modelVideoEmbeds;
  moneyFormat: typeof moneyFormat;
  nightlyViewsSync: typeof nightlyViewsSync;
  notificationEvents: typeof notificationEvents;
  notificationMessage: typeof notificationMessage;
  notificationWindow: typeof notificationWindow;
  notifications: typeof notifications;
  notifyApi: typeof notifyApi;
  opsDigest: typeof opsDigest;
  passwordReset: typeof passwordReset;
  payCycle: typeof payCycle;
  payWindow: typeof payWindow;
  payments: typeof payments;
  paymentsView: typeof paymentsView;
  permissionCoverage: typeof permissionCoverage;
  permissionProbe: typeof permissionProbe;
  permissions: typeof permissions;
  personnes: typeof personnes;
  platforms: typeof platforms;
  postUrlDate: typeof postUrlDate;
  postUrlResolution: typeof postUrlResolution;
  postUrlShape: typeof postUrlShape;
  postWindow: typeof postWindow;
  posthogApi: typeof posthogApi;
  posthogSync: typeof posthogSync;
  pricing: typeof pricing;
  pricingSnapshotMigration: typeof pricingSnapshotMigration;
  profitability: typeof profitability;
  profitabilityMath: typeof profitabilityMath;
  progression: typeof progression;
  projectLifecycle: typeof projectLifecycle;
  projectLifecycleRules: typeof projectLifecycleRules;
  projectPurgeTables: typeof projectPurgeTables;
  projects: typeof projects;
  provisionAdmin: typeof provisionAdmin;
  publicShare: typeof publicShare;
  publicShares: typeof publicShares;
  publicationLateness: typeof publicationLateness;
  publications: typeof publications;
  quadrant: typeof quadrant;
  quadrantSettings: typeof quadrantSettings;
  quadrantSync: typeof quadrantSync;
  radar: typeof radar;
  radarApi: typeof radarApi;
  reminderGrouping: typeof reminderGrouping;
  remunerate: typeof remunerate;
  retentionCost: typeof retentionCost;
  reviewQueue: typeof reviewQueue;
  roles: typeof roles;
  rushScriptEligibility: typeof rushScriptEligibility;
  rushStatus: typeof rushStatus;
  rushes: typeof rushes;
  scriptAnalytics: typeof scriptAnalytics;
  scriptDecision: typeof scriptDecision;
  scriptNotif: typeof scriptNotif;
  scriptSeedData: typeof scriptSeedData;
  scriptZonesSetting: typeof scriptZonesSetting;
  scripts: typeof scripts;
  segmentFunnel: typeof segmentFunnel;
  settledCycles: typeof settledCycles;
  showcase: typeof showcase;
  snapchatInternal: typeof snapchatInternal;
  snapchatPostUrl: typeof snapchatPostUrl;
  snapchatPublicPage: typeof snapchatPublicPage;
  snapshotMatching: typeof snapshotMatching;
  snytchDrive: typeof snytchDrive;
  soloDays: typeof soloDays;
  storage: typeof storage;
  storageCleanup: typeof storageCleanup;
  syncScope: typeof syncScope;
  talentBriefFields: typeof talentBriefFields;
  talentPay: typeof talentPay;
  talentRetainer: typeof talentRetainer;
  talentRushFields: typeof talentRushFields;
  targetAccountSwap: typeof targetAccountSwap;
  team: typeof team;
  tiktokInternal: typeof tiktokInternal;
  tiktokPublicPage: typeof tiktokPublicPage;
  trackerData: typeof trackerData;
  unitEconomics: typeof unitEconomics;
  viewCounters: typeof viewCounters;
  viewsDaily: typeof viewsDaily;
  viewsPulse: typeof viewsPulse;
  viewsPulseCore: typeof viewsPulseCore;
  warmup: typeof warmup;
  warmupGuideFused: typeof warmupGuideFused;
  warmupMode: typeof warmupMode;
  whopApi: typeof whopApi;
  whopClients: typeof whopClients;
  whopLedgerApi: typeof whopLedgerApi;
  whopNotifyTriggers: typeof whopNotifyTriggers;
  whopPaymentsAccess: typeof whopPaymentsAccess;
  whopRevenue: typeof whopRevenue;
  whopSync: typeof whopSync;
  windowCacheTtl: typeof windowCacheTtl;
  youtubeApi: typeof youtubeApi;
  youtubeChannel: typeof youtubeChannel;
  youtubeSync: typeof youtubeSync;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

export declare const components: {};
